export const nl = {
  title: "KBO Evidence Desk",
  login: "Aanmelden",
  email: "E-mailadres",
  password: "Wachtwoord",
  failed: "Aanmelden mislukt. Controleer uw gegevens.",
  logout: "Afmelden",
  welcome: "U bent aangemeld.",
  pending: "Even geduld...",
  noAccess: "Uw account heeft nog geen toegang als medewerker.",
  intro: "Meld u aan met uw medewerkersaccount.",
  attribution:
    "publieke KBO gegevens, verrijkt met adressen uit het Vlaamse Adressenregister.",
};

export const uiNl = {
  close: "Sluiten",
  more: "Meer",
  previous: "Vorige",
  next: "Volgende",
  previousSlide: "Vorige dia",
  nextSlide: "Volgende dia",
  previousPage: "Ga naar vorige pagina",
  nextPage: "Ga naar volgende pagina",
  morePages: "Meer pagina's",
  breadcrumb: "Kruimelpad",
  pagination: "Paginering",
  toggleSidebar: "Zijbalk wisselen",
  loading: "Laden",
  closeToast: "Melding sluiten",
  commands: "Opdrachten",
  searchCommands: "Zoek een opdracht...",
  scrollEnd: "Naar het einde",
  scrollStart: "Naar het begin",
  sidebar: "Zijbalk",
  sidebarDescription: "Toont de mobiele zijbalk.",
  submit: "Verzenden",
  skip: "Overslaan",
} as const;
export const deskNl = {
  brand: "Straatbeeld",
  subtitle: "Lokale economie",
  municipality: "Gemeente",
  town: "Schoten",
  demo: "Steekproef",
  demoNote:
    "Gedeeltelijke VKBO-steekproef. Beoordelingen worden opgeslagen; alleen goedgekeurde wijzigingen zijn exporteerbaar. Het officiële register wordt niet gewijzigd.",
  search: "Straat, handelsnaam of ondernemingsnummer",
  searchLabel: "Records zoeken",
  records: "records",
  review: "Nazicht",
  nav: {
    overview: "Overzicht",
    street: "Straatbeeld",
    map: "Kaart",
    review: "Nazicht",
    history: "Historiek",
    sources: "Bronnen",
    states: "Toestanden",
  },
  titles: {
    overview: "Wat vandaag nazicht vraagt",
    street: "Alle straten",
    map: "Adreslocaties",
    review: "Voorstellen ter beoordeling",
    history: "Historiek",
    sources: "Bronnen en gemeente",
    states: "Toestanden",
  },
  descriptions: {
    overview:
      "Overzicht van het activiteitenbeeld voor Schoten. Niets wordt gepubliceerd zonder uw bevestiging.",
    street:
      "Elk adres met registerstatus, gedateerd bewijs en een zekerheidsmarkering. Open een dossier om het bewijs te bekijken.",
    map: "Adreslocaties uit de aangeleverde steekproef. Gebruik de zoekbalk om te filteren.",
    review:
      "Voorstellen worden pas doorgevoerd na uw bevestiging. Afgewezen voorstellen blijven in de historiek staan, met uw motivering.",
    history: "Opgeslagen beslissingen met bron, medewerker en tijdstip.",
    sources: "Gekoppelde register- en websitebronnen met ophaaldatum.",
    states: "Voorbeelden van laden, lege resultaten en een onbeschikbare bron.",
  },
  stats: [
    "Records in beeld",
    "Te controleren",
    "Ondernemingsdossier ontbreekt",
    "Wachtrij",
  ],
  statNotes: [
    "echte vestigingen uit de steekproef",
    "geen recent bewijs van activiteit",
    "koppeling met onderneming ontbreekt",
    "voorstellen wachten op beoordeling",
  ],
  streetTitle: "Straten met openstaande vragen",
  streetNote: "Gesorteerd op aantal openstaande voorstellen",
  recent: "Recent beoordeeld",
  recentNote: "Opgeslagen beoordelingen",
  noHistory: "Nog geen beslissingen",
  noHistoryNote: "Beoordeel een voorstel om de historiek te vullen.",
  columns: [
    "Adres",
    "Onderneming / vestiging",
    "Register",
    "Bewijs van activiteit",
    "Bron opgehaald",
    "Activiteitsbeeld",
    "Voorstel",
  ],
  evidence: "Bewijs",
  confirm: "Bevestigen",
  reject: "Afwijzen",
  later: "Later",
  confirmed: "Bevestigd",
  rejected: "Afgewezen",
  relation: "Registerrelatie",
  establishment: "Vestigingsnr.",
  enterprise: "Onderneming",
  seat: "Maatsch. zetel",
  legal: "Rechtstoestand onderneming",
  contact: "Contact",
  proposal: "Voorstel",
  certainty: "Activiteitsbeeld",
  placeholderSource: "Voorbeeldbron — geen verifieerbare link beschikbaar",
  pending:
    "Nog niet beoordeeld. Niets verlaat het systeem zonder uw bevestiging.",
  source: "Hoofdbron",
  decision: "Beslissing",
  time: "Tijdstip",
  record: "Record",
  change: "Wijziging",
  employee: "Medewerker",
  status: "Status",
  reason: "Motivering (komt in de historiek)",
  reasonPlaceholder: "Vermeld waarop u uw beslissing baseert.",
  confirmTitle: "Wijziging bevestigen",
  rejectTitle: "Voorstel afwijzen",
  dialogNote:
    "Uw beoordeling wordt met uw account en het tijdstip opgeslagen. Alleen goedgekeurde waarden komen in de export.",
  cancel: "Annuleren",
  saveConfirm: "Bevestigen en loggen",
  saveReject: "Afwijzen en loggen",
  legend: "Legende",
  high: "Hoge zekerheid",
  medium: "Middelmatige zekerheid",
  low: "Lage zekerheid",
  mapNote:
    "De kaart toont alleen de twaalf voorbeeldrecords. Verdachte coördinaten moeten apart worden gevalideerd.",
  toStreet: "Naar straatbeeld",
  activeTown: "Actieve gemeente",
  region: "Gemeente of regio (provincie Antwerpen)",
  townNote:
    "Voor een andere gemeente zijn een VKBO-filter op NIS-code, adresgegevens en gevalideerde bronnen nodig.",
  sourcePending: "Niet gekoppeld",
  sample: "VKBO-steekproef: 1.000 records",
  updated: "opgehaald 07-09-2026",
  licence: "Modellicentie Gratis Hergebruik v1.0",
  sampleNote:
    "De VKBO-steekproef bevat 1.000 records en is niet het volledige register. Lokale activiteit is niet automatisch vastgesteld.",
  loading: "Laden",
  empty: "Leeg",
  error: "Bron faalt",
  loadingNote:
    "Demonstratie: bewijs wordt opgehaald · 3 van 8 bronnen bevraagd",
  emptyTitle: "Geen records op dit adres",
  emptyNote: "Probeer een andere straat, handelsnaam of ondernemingsnummer.",
  clear: "Alle records tonen",
  errorTitle: "Bron onbeschikbaar",
  errorDetail: "Kaartdienst antwoordde niet",
  errorNote:
    "De overige bronnen kunnen wel worden bekeken. Zonder deze bron blijft het resultaat onvolledig.",
  retry: "Opnieuw proberen",
  continue: "Zonder deze bron verdergaan",
  noQueue: "Alle voorstellen zijn beoordeeld",
  noQueueNote: "Uw beslissingen staan opgeslagen in de historiek.",
  export: "CSV exporteren",
  open: "open",
};

export const deskSources = [
  "VKBO ondernemingen en vestigingseenheden V3",
  "Vlaams Adressenregister",
  "Gemeentelijk vergunningsregister",
  "Kaartdienst (openingsuren, recensies)",
  "Eigen terreinwaarnemingen",
  "FAVV-registraties",
];
export const sidebarNl = {
  workspace: "Werkruimte",
  management: "Beheer",
  demo: "Steekproef",
  account: "Mijn account",
  signedIn: "Aangemeld als",
  officer: "Medewerker lokale economie",
  dataset: "VKBO-steekproef",
  municipality: "Gemeente Schoten",
  shortcut: "Zijbalk wisselen",
  sourceDetails: "Bronnen bekijken",
};
