export const nl = {
  title: "KBO Evidence Desk",
  login: "Aanmelden",
  email: "E-mailadres",
  password: "Wachtwoord",
  failed: "Aanmelden mislukt. Controleer uw gegevens.",
  logout: "Afmelden",
  welcome: "U bent aangemeld.",
  pending: "Even geduld...",
  noAccess: "Uw account heeft nog geen toegang als medewerker.",
  intro: "Meld u aan met uw medewerkersaccount.",
  attribution:
    "publieke KBO gegevens, verrijkt met adressen uit het Vlaamse Adressenregister.",
};

export const commandNl = {
  title: "Snel naar",
  trigger: "Snel zoeken",
  description: "Vind een zaak of straat, of ga naar een andere pagina.",
  placeholder: "Straat, onderneming of werkblad…",
  empty: "Geen resultaten gevonden.",
  search: "Straatbeeld",
  searchFor: "Zoek naar",
  allRecords: "Alle records bekijken",
  navigation: "Werkbladen",
  records: "Dossiers · registergegevens",
  move: "Navigeren",
  open: "Openen",
  close: "Sluiten",
} as const;

export const mapNl = {
  title: "Register op de kaart",
  search: "Zoek straat, naam of registernummer…",
  searchLabel: "Kaartrecords zoeken",
  allKinds: "Alle recordtypes",
  kind: "Recordtype",
  onderneming: "Ondernemingen",
  vestiging: "Vestigingen",
  entity: "Onderneming",
  establishment: "Vestigingseenheid",
  confidence: "Zekerheid",
  allConfidence: "Alle zekerheden",
  unknown: "onbekend",
  unassessed: "Nog niet beoordeeld",
  high: "Hoog",
  medium: "Middel",
  low: "Laag",
  fit: "Toon resultaten",
  reset: "Terug naar gemeente",
  zoomIn: "Inzoomen",
  zoomOut: "Uitzoomen",
  fullscreen: "Volledig scherm wisselen",
  north: "Noorden boven",
  close: "Sluiten",
  retry: "Opnieuw proberen",
  loading: "Registerrecords laden…",
  mapLoading: "Kaart laden…",
  refreshing: "Vernieuwen…",
  refresh: "Gegevens vernieuwen",
  loadError:
    "Registergegevens zijn niet bereikbaar. De achtergrondkaart blijft beschikbaar. Controleer de API en probeer opnieuw.",
  tileError:
    "De achtergrondkaart kon niet volledig laden. De resultaten blijven beschikbaar.",
  webglError:
    "De kaart kan in deze browser niet worden weergegeven. Gebruik de resultatenlijst of probeer een browser met WebGL.",
  empty: "Geen registerrecords gevonden",
  emptyNote:
    "Probeer een andere zoekterm of wis de filters. Een lege kaart betekent niet dat hier geen ondernemingen zijn.",
  noData: "Er zijn nog geen registerrecords ingeladen.",
  clear: "Filters wissen",
  results: "Resultaten",
  visibleOnly: "Alleen in kaartbeeld",
  allResults: "Alle resultaten",
  located: "op de kaart",
  missing: "Locatie onbekend",
  suspect: "Coördinaten te controleren",
  unlocatedNote:
    "Records zonder betrouwbare locatie blijven in de lijst staan. Ze worden niet op de kaart geplaatst.",
  select: "Selecteer een record",
  selectNote:
    "Klik op een punt of een resultaat om registergegevens en bewijs te bekijken. Klik op een cluster om in te zoomen.",
  detail: "Register en bewijs",
  address: "Adres",
  number: "Registernummer",
  parent: "Ondernemingsnummer van de zetel",
  externalSeat: "Maatschappelijke zetel buiten Schoten",
  legalStatus: "Rechtstoestand onderneming",
  noName: "Naam onbekend",
  lastSeen: "Laatste waarneming",
  evidence: "Bewijs van activiteit",
  noEvidence: "Geen volledig herleidbaar bewijs van activiteit gevonden.",
  incompleteEvidence:
    "Onvolledige bronvermeldingen tellen niet als bewijs van activiteit.",
  reasons: "Bijdragende signalen",
  proposal: "Voorstel",
  source: "Bron openen",
  detailError: "Het dossier kon niet worden geladen.",
  live: "Registergegevens via API",
  registerNote:
    "Een registervermelding is geen bevestiging van actuele activiteit. De geladen dataset kan onvolledig zijn.",
  bbox: "Controlekader gemeente",
  bboxNote:
    "Het kader komt uit de gemeenteconfiguratie; het is geen officiële gemeentegrens.",
  help: "Sleep om te verplaatsen · scroll of gebruik +/− om te zoomen",
  legend: "Zekerheid van activiteit",
  noPublish: "Deze kaart wijzigt of publiceert geen registergegevens.",
  mapLabel: "Interactieve kaart met registerrecords",
  overlapping:
    "Records op dit adres zijn afzonderlijk te openen in de resultatenlijst.",
  mapAttribution: "Kaartbronnen",
  toggleAttribution: "Kaartbronnen tonen",
  mapKeyboard:
    "Gebruik de pijltjestoetsen om te verplaatsen en + of − om te zoomen.",
  locate: "Mijn locatie",
  page: "Pagina",
  previous: "Vorige",
  next: "Volgende",
} as const;

export const uiNl = {
  close: "Sluiten",
  more: "Meer",
  previous: "Vorige",
  next: "Volgende",
  previousSlide: "Vorige dia",
  nextSlide: "Volgende dia",
  previousPage: "Ga naar vorige pagina",
  nextPage: "Ga naar volgende pagina",
  morePages: "Meer pagina's",
  breadcrumb: "Kruimelpad",
  pagination: "Paginering",
  toggleSidebar: "Zijbalk wisselen",
  loading: "Laden",
  closeToast: "Melding sluiten",
  commands: "Opdrachten",
  searchCommands: "Zoek een opdracht...",
  scrollEnd: "Naar het einde",
  scrollStart: "Naar het begin",
  sidebar: "Zijbalk",
  sidebarDescription: "Toont de mobiele zijbalk.",
  submit: "Verzenden",
  skip: "Overslaan",
} as const;
export const deskNl = {
  brand: "Straatbeeld",
  subtitle: "Lokale economie",
  municipality: "Gemeente",
  town: "Schoten",
  demo: "Steekproef",
  demoNote:
    "Gedeeltelijke VKBO-steekproef. Beoordelingen worden opgeslagen; alleen goedgekeurde wijzigingen zijn exporteerbaar. Het officiële register wordt niet gewijzigd.",
  search: "Straat, handelsnaam of ondernemingsnummer",
  searchLabel: "Records zoeken",
  records: "records",
  review: "Wijzigingen",
  workspaceLabel: "Werkruimte · Lokale economie",
  focusLabel: "Uw volgende stap",
  focusTitle: "Van signaal naar een onderbouwd besluit.",
  focusNote:
    "Bekijk het bewijs, controleer de registerrelatie en leg uw beoordeling vast. U houdt de regie.",
  startReview: "Voorstellen bekijken",
  exploreStreets: "Straten verkennen",
  waitingReview: "voorstellen voor uw nazicht",
  sessionProgress: "Beoordeeld in deze sessie",
  reviewFirst: "Eerstvolgende voorstellen",
  reviewFirstNote: "Open een dossier en bekijk de onderliggende signalen.",
  viewAll: "Alles bekijken",
  openDossier: "Dossier bekijken",
  historyEmptyTitle: "Hier groeit uw beslissingsspoor",
  historyEmptyNote:
    "Na uw eerste beoordeling vindt u hier de beslissing, het bewijs en het tijdstip terug.",
  approvalNote: "Publicatie alleen na uw bevestiging",
  nav: {
    overview: "Start",
    street: "Zaken",
    map: "Kaart",
    review: "Wijzigingen",
    history: "Historiek",
    sources: "Over deze gegevens",
    states: "Toestanden",
  },
  titles: {
    overview: "Wat vandaag nazicht vraagt",
    street: "Alle straten",
    map: "Adreslocaties",
    review: "Voorstellen ter beoordeling",
    history: "Historiek",
    sources: "Bronnen en gemeente",
    states: "Toestanden",
  },
  descriptions: {
    overview:
      "Overzicht van het activiteitenbeeld voor Schoten. Niets wordt gepubliceerd zonder uw bevestiging.",
    street:
      "Elk adres met registerstatus, gedateerd bewijs en een zekerheidsmarkering. Open een dossier om het bewijs te bekijken.",
    map: "Verken registerrecords op de kaart. Selecteer een locatie en bekijk de bronnen achter het activiteitenbeeld.",
    review:
      "Voorstellen worden pas doorgevoerd na uw bevestiging. Afgewezen voorstellen blijven in de historiek staan, met uw motivering.",
    history: "Opgeslagen beslissingen met bron, medewerker en tijdstip.",
    sources: "Gekoppelde register- en websitebronnen met ophaaldatum.",
    states: "Voorbeelden van laden, lege resultaten en een onbeschikbare bron.",
  },
  stats: [
    "Records in beeld",
    "Te controleren",
    "Ondernemingsdossier ontbreekt",
    "Wachtrij",
  ],
  statNotes: [
    "echte vestigingen uit de steekproef",
    "geen recent bewijs van activiteit",
    "koppeling met onderneming ontbreekt",
    "voorstellen wachten op beoordeling",
  ],
  streetTitle: "Straten met openstaande vragen",
  streetNote: "Gesorteerd op aantal openstaande voorstellen",
  recent: "Recent beoordeeld",
  recentNote: "Opgeslagen beoordelingen",
  noHistory: "Nog geen beslissingen",
  noHistoryNote: "Beoordeel een voorstel om de historiek te vullen.",
  columns: [
    "Adres",
    "Onderneming / vestiging",
    "Register",
    "Bewijs van activiteit",
    "Bron opgehaald",
    "Activiteitsbeeld",
    "Voorstel",
  ],
  evidence: "Bewijs",
  confirm: "Bevestigen",
  reject: "Afwijzen",
  later: "Later",
  confirmed: "Bevestigd",
  rejected: "Afgewezen",
  relation: "Registerrelatie",
  establishment: "Vestigingsnr.",
  enterprise: "Onderneming",
  seat: "Maatsch. zetel",
  legal: "Rechtstoestand onderneming",
  contact: "Contact",
  proposal: "Voorstel",
  certainty: "Activiteitsbeeld",
  placeholderSource: "Voorbeeldbron — geen verifieerbare link beschikbaar",
  pending:
    "Nog niet beoordeeld. Niets verlaat het systeem zonder uw bevestiging.",
  source: "Hoofdbron",
  decision: "Beslissing",
  time: "Tijdstip",
  record: "Record",
  change: "Wijziging",
  employee: "Medewerker",
  status: "Status",
  reason: "Motivering (komt in de historiek)",
  reasonPlaceholder: "Vermeld waarop u uw beslissing baseert.",
  confirmTitle: "Wijziging bevestigen",
  rejectTitle: "Voorstel afwijzen",
  dialogNote:
    "Uw beoordeling wordt met uw account en het tijdstip opgeslagen. Alleen goedgekeurde waarden komen in de export.",
  cancel: "Annuleren",
  saveConfirm: "Bevestigen en loggen",
  saveReject: "Afwijzen en loggen",
  legend: "Legende",
  high: "Hoge zekerheid",
  medium: "Middelmatige zekerheid",
  low: "Lage zekerheid",
  mapNote:
    "De kaart toont alleen de twaalf voorbeeldrecords. Verdachte coördinaten moeten apart worden gevalideerd.",
  toStreet: "Naar straatbeeld",
  activeTown: "Actieve gemeente",
  region: "Gemeente of regio (provincie Antwerpen)",
  townNote:
    "Voor een andere gemeente zijn een VKBO-filter op NIS-code, adresgegevens en gevalideerde bronnen nodig.",
  sourcePending: "Niet gekoppeld",
  sample: "VKBO-steekproef: 1.000 records",
  updated: "opgehaald 07-09-2026",
  licence: "Modellicentie Gratis Hergebruik v1.0",
  sampleNote:
    "De VKBO-steekproef bevat 1.000 records en is niet het volledige register. Lokale activiteit is niet automatisch vastgesteld.",
  loading: "Laden",
  empty: "Leeg",
  error: "Bron faalt",
  loadingNote:
    "Demonstratie: bewijs wordt opgehaald · 3 van 8 bronnen bevraagd",
  emptyTitle: "Geen records op dit adres",
  emptyNote: "Probeer een andere straat, handelsnaam of ondernemingsnummer.",
  clear: "Alle records tonen",
  errorTitle: "Bron onbeschikbaar",
  errorDetail: "Kaartdienst antwoordde niet",
  errorNote:
    "De overige bronnen kunnen wel worden bekeken. Zonder deze bron blijft het resultaat onvolledig.",
  retry: "Opnieuw proberen",
  continue: "Zonder deze bron verdergaan",
  noQueue: "Alle voorstellen zijn beoordeeld",
  noQueueNote: "Uw beslissingen staan opgeslagen in de historiek.",
  export: "CSV exporteren",
  open: "open",
};

export const deskSources = [
  "VKBO ondernemingen en vestigingseenheden V3",
  "Vlaams Adressenregister",
  "Gemeentelijk vergunningsregister",
  "Kaartdienst (openingsuren, recensies)",
  "Eigen terreinwaarnemingen",
  "FAVV-registraties",
];
export const sidebarNl = {
  workspace: "Werkruimte",
  management: "Beheer",
  demo: "Steekproef",
  account: "Mijn account",
  signedIn: "Aangemeld als",
  officer: "Medewerker lokale economie",
  dataset: "VKBO-steekproef",
  municipality: "Gemeente Schoten",
  shortcut: "Zijbalk wisselen",
  sourceDetails: "Bronnen bekijken",
};

export const chartNl = {
  section: "Interactief gegevensoverzicht",
  records: "records",
  high: "Hoog",
  medium: "Middel",
  low: "Laag",
  demo: "Steekproef",
  confidenceTitle: "Hoe sterk is het bewijs?",
  confidenceNote:
    "Verdeling van het activiteitsbeeld in de gekoppelde dossiers.",
  selectConfidence: "Filter op zekerheid",
  selectHint: "Selecteer een niveau om de bijbehorende dossiers te bekijken.",
  reset: "Wissen",
  empty: "Geen records met dit zekerheidsniveau.",
  demoNote:
    "Registervermeldingen bewijzen geen actuele lokale activiteit. Controleer de bronnen per dossier.",
  streetTitle: "Waar is nazicht nodig?",
  streetNote: "Vergelijk de drukste 12 straten in deze steekproef.",
  scope: "Records vergelijken",
  all: "Alle records",
  open: "Open voorstellen",
  noOpen: "Alle voorstellen zijn beoordeeld.",
  openStreet: "Open het straatbeeld",
  streetFooter:
    "Open voorstellen wijzigen na een beoordeling. Straatknoppen openen alle records van die straat.",
};

export const tableNl = {
  search: "Zoeken in deze tabel…",
  selectPage: "Alle rijen op deze pagina selecteren",
  selectRow: "Rij selecteren",
  is: "is",
  addFilter: "Filter toevoegen",
  removeFilter: "Filter verwijderen",
  clearFilters: "Filters wissen",
  columns: "Kolommen",
  unknown: "Onbekend",
  selected: "geselecteerd",
  withinFilters: "binnen de filters",
  selectedOnly: "Alleen selectie",
  clearSelection: "Selectie wissen",
  noResults: "Geen records voor deze filters.",
  of: "van",
  records: "records",
  perPage: "Per pagina",
  page: "Pagina",
  previous: "Vorige pagina",
  next: "Volgende pagina",
};

export const uxNl = {
  activity: {
    supported:
      "Bronnen ondersteunen lokale activiteit; bekijk de datums en reikwijdte.",
    conflicting:
      "Bronnen geven tegenstrijdige signalen over lokale activiteit.",
    insufficient: "Actuele lokale activiteit is nog niet vastgesteld.",
    needs_check: "De lokale activiteit moet nog worden gecontroleerd.",
  },

  titles: {
    overview: "Wat wilt u controleren?",
    street: "Zaken in Schoten",
    map: "Zaken in Schoten",
    review: "Wijzigingen controleren",
    history: "Historiek",
    sources: "Over deze gegevens",
    states: "Voorbeeldtoestanden · ontwikkeling",
  },
  search: "Zoek een zaak of straat",
  searchHelp: "U kunt ook zoeken op een ondernemings- of vestigingsnummer.",
  find: "Zoeken",
  clear: "Zoekopdracht wissen",
  list: "Lijst",
  map: "Kaart",
  back: "Terug naar zaken",
  backReview: "Terug naar wijzigingen",
  loading: "Zaken laden…",
  retry: "Opnieuw proberen",
  business: "Zaak",
  address: "Adres",
  change: "Open wijziging",
  noChange: "Geen open wijziging",
  noChangeNote:
    "Dit betekent niet dat alle gegevens of de activiteit gecontroleerd zijn.",
  coverage: "U bekijkt een deel van de geregistreerde zaken in Schoten.",
  about: "Over deze gegevens",
  start: "Begin met controleren",
  allChanges: "Alle wijzigingen bekijken",
  noPending: "Geen wijzigingen om te beoordelen",
  noPendingNote:
    "U kunt een zaak opzoeken om de beschikbare gegevens en bronnen te bekijken.",
  check: "Controleren",
  view: "Bekijk zaak",
  pending: "Te controleren",
  before: "In onze werklijst",
  original: "Vóór dit voorstel",
  proposed: "Voorgesteld",
  unknown: "Niet bekend",
  reason: "Waarom stellen we dit voor?",
  evidence: "Wat zeggen de bronnen?",
  compare: "Vergelijk deze bronnen",
  compareNote:
    "Controleer de genoemde waarden in alle onderstaande bronnen. Ze zijn niet automatisch met elkaar verzoend.",
  conflict: "De bronnen spreken elkaar tegen",
  conflictNote: "Bekijk de verschillende waarden voordat u beslist.",
  localCheck: "Nog geen duidelijk bewijs voor deze winkel",
  localCheckNote:
    "Informatie over het hoofdkantoor is niet automatisch van toepassing op deze vestiging.",
  source: "Bron openen",
  fetched: "Bron opgehaald op",
  observed: "Waargenomen op",
  cached: "Eerder opgehaalde bron",
  local: "Gaat over deze winkel",
  enterprise: "Gaat over het hoofdkantoor",
  unknownScope: "Toepasselijkheid op deze winkel is onbekend",
  approve: "Goedkeuren",
  edit: "Waarde aanpassen",
  reject: "Afwijzen",
  later: "Later bekijken",
  save: "Aanpassing goedkeuren",
  saveReject: "Afwijzing opslaan",
  saving: "Opslaan…",
  cancel: "Annuleren",
  note: "Toelichting (optioneel)",
  adjusted: "Waarde voor de werklijst",
  officialNote:
    "U past de gemeentelijke werklijst aan. De officiële KBO verandert niet.",
  approved: "Goedgekeurd",
  rejected: "Afgewezen",
  pendingStatus: "Nog te beoordelen",
  next: "Volgende wijziging",
  revise: "Beslissing opnieuw bekijken",
  saved: "Opgeslagen in de werklijst.",
  rejectedSaved: "Voorstel afgewezen.",
  stale:
    "Deze wijziging is intussen beoordeeld. Uw invoer is bewaard. Bekijk de actuele beslissing voordat u opnieuw beslist.",
  acknowledge: "Actuele beslissing bekeken — opnieuw beoordelen",
  registry: "Officiële bedrijfsgegevens",
  allSources: "Alle bronnen",
  audit: "Eerdere beslissingen",
  contact: "Gecontroleerde contactgegevens",
  noContact: "Er zijn nog geen goedgekeurde contactgegevens.",
  foundContact: "Contactgegevens gevonden in bronnen",
  sourceOnly: "Brongegeven — niet goedgekeurd",
  refresh: "Bronnen opnieuw controleren",
  refreshing: "Bronnen controleren…",
  export: "Goedgekeurde wijzigingen exporteren",
  exportNote:
    "Alleen de laatste goedgekeurde wijzigingen staan in dit bestand. Het officiële register verandert niet.",
  exportScope: "Welke zaken wilt u exporteren?",
  allStreets: "Alle straten in Schoten",
  download: "CSV downloaden",
  noExport: "Geen goedgekeurde wijzigingen binnen deze selectie.",
  historyEmpty: "Nog geen beslissingen opgeslagen",
  historyNote:
    "Na een beoordeling verschijnen de wijziging, bronnen en toelichting hier.",
  historyChange: "Wijziging",
  decision: "Beslissing",
  date: "Datum",
  details: "Details bekijken",
  employee: "Beoordeeld door",
  revision: "Revisie",
  discardTitle: "U heeft nog niet opgeslagen",
  discardNote: "Wilt u uw invoer behouden of verlaten zonder op te slaan?",
  keep: "Verder bewerken",
  discard: "Invoer verwerpen",
  noEvidence: "Er is geen herleidbaar bewijs voor dit voorstel beschikbaar.",
  unavailable: "Deze zaak is niet beschikbaar.",
  previous: "Vorige pagina",
  nextPage: "Volgende pagina",
  filters: "Filters",
  street: "Straat",
} as const;
