// Design fixtures from the supplied Claude export. Not verified business data.
export type DemoRecord = {
  adres: string;
  naam: string;
  soort: string;
  register: string;
  laatste: string;
  zekerheid: "Hoog" | "Middel" | "Laag";
  voorstel: string;
  voorstelLang: string;
  vestNr: string;
  ondNr: string;
  zetel: string;
  rechtstoestand: string;
  contact: string;
  contactNiveau: string;
  contactBron: string;
  x: number;
  y: number;
  bewijs: { waarneming: string; bron: string; datum: string; url: string }[];
};
export const demoRecords: DemoRecord[] = [
  {
    adres: "Paalstraat 12",
    naam: "Bakkerij De Schoof",
    soort: "vestigingseenheid",
    register: "Actief",
    laatste: "2026-09-05",
    zekerheid: "Hoog",
    voorstel: "Geen actie",
    voorstelLang:
      "Record klopt. Bewijs bevestigt activiteit; geen wijziging voorgesteld.",
    vestNr: "2.271.884.913",
    ondNr: "0454.812.209",
    zetel: "Paalstraat 12, Schoten",
    rechtstoestand: "Normale toestand",
    contact: "03 658 41 12 · info@deschoof.be",
    contactNiveau: "vestiging",
    contactBron: "eigen website, gecontroleerd 05-09-2026",
    bewijs: [
      {
        waarneming: "Website actief, openingsuren vermeld",
        bron: "deschoof.be",
        datum: "2026-09-05",
        url: "#",
      },
      {
        waarneming: "Openingsuren op kaartdienst bevestigd",
        bron: "kaartdienst",
        datum: "2026-09-05",
        url: "#",
      },
      {
        waarneming: "Terrasvergunning 2026 op naam van deze vestiging",
        bron: "vergunningsregister",
        datum: "2026-03-18",
        url: "#",
      },
    ],
    x: 12,
    y: 36,
  },
  {
    adres: "Paalstraat 14",
    naam: "Adviesbureau Vermeiren BV",
    soort: "vestiging · zetel elders",
    register: "Actief",
    laatste: "—",
    zekerheid: "Laag",
    voorstel: "Ter controle: mogelijk niet meer actief",
    voorstelLang:
      'Geen enkel publiek spoor van activiteit sinds 2023. Voorstel: markeren als "mogelijk inactief" en opnemen in de ronde terreinbezoeken.',
    vestNr: "2.194.556.031",
    ondNr: "0688.443.117",
    zetel: "Lange Leemstraat 118, Antwerpen",
    rechtstoestand: "Normale toestand",
    contact: "contactgegevens onbekend",
    contactNiveau: "geen bron",
    contactBron: "niets in register of GeoJSON",
    bewijs: [
      {
        waarneming: "Geen website, geen vermelding in bedrijvengidsen",
        bron: "zoekopdracht",
        datum: "2026-09-12",
        url: "#",
      },
      {
        waarneming: "Geen recente vergunning of melding",
        bron: "vergunningsregister",
        datum: "2026-09-12",
        url: "#",
      },
    ],
    x: 18,
    y: 33,
  },
  {
    adres: "Paalstraat 20",
    naam: "Kapsalon Lynn",
    soort: "niet in register op dit adres",
    register: "Ontbreekt",
    laatste: "2026-09-05",
    zekerheid: "Middel",
    voorstel: "Nazicht: vestiging ontbreekt of adres verkeerd",
    voorstelLang:
      "Zichtbaar open zaak zonder vestigingseenheid op dit adres. Voorstel: vestiging aanmelden bij de onderneming en het adres laten corrigeren.",
    vestNr: "ontbreekt",
    ondNr: "vermoedelijk 0761.209.544",
    zetel: "Onbekend",
    rechtstoestand: "n.v.t.",
    contact: "03 685 77 90",
    contactNiveau: "vestiging (via boekingssite)",
    contactBron: "boekingsplatform, 05-09-2026",
    bewijs: [
      {
        waarneming: "Uithangbord en openingsuren aan het pand",
        bron: "terreinbezoek",
        datum: "2026-09-05",
        url: "#",
      },
      {
        waarneming: "48 recensies, meest recente vorige week",
        bron: "kaartdienst",
        datum: "2026-09-10",
        url: "#",
      },
    ],
    x: 26,
    y: 40,
  },
  {
    adres: "Paalstraat 24",
    naam: "Slagerij Peeters",
    soort: "vestigingseenheid",
    register: "Actief",
    laatste: "2026-08-28",
    zekerheid: "Middel",
    voorstel: "Ter controle: verouderd webspoor",
    voorstelLang:
      "Website bestaat nog maar werd sinds 2019 niet bijgewerkt. Voorstel: telefonisch nazicht voor de zekerheid op Hoog gaat.",
    vestNr: "2.108.773.402",
    ondNr: "0521.884.006",
    zetel: "Paalstraat 24, Schoten",
    rechtstoestand: "Normale toestand",
    contact: "03 645 21 88",
    contactNiveau: "vestiging",
    contactBron: "GeoJSON-veld Telefoonnummer",
    bewijs: [
      {
        waarneming: "Website online, laatste bericht 2019",
        bron: "eigen website",
        datum: "2026-08-28",
        url: "#",
      },
      {
        waarneming: "FAVV-registratie actief",
        bron: "FAVV",
        datum: "2026-06-01",
        url: "#",
      },
    ],
    x: 34,
    y: 35,
  },
  {
    adres: "Paalstraat 31",
    naam: "Horeca Invest NV",
    soort: "rechtspersoon · zetel hier",
    register: "Actief",
    laatste: "—",
    zekerheid: "Laag",
    voorstel: "Nazicht: zetel zonder vestiging",
    voorstelLang:
      "Maatschappelijke zetel op dit adres, maar geen vestigingseenheid en geen zichtbare activiteit. Waarschijnlijk een brievenbusadres — niet meenemen in het activiteitenbeeld.",
    vestNr: "geen",
    ondNr: "0716.554.882",
    zetel: "Paalstraat 31, Schoten",
    rechtstoestand: "Normale toestand",
    contact: "info@horecainvest.be",
    contactNiveau: "centrale zetel",
    contactBron: "GeoJSON-veld Email",
    bewijs: [
      {
        waarneming: "Geen vestigingseenheid op dit adres in de steekproef",
        bron: "VKBO",
        datum: "2026-09-07",
        url: "#",
      },
    ],
    x: 44,
    y: 38,
  },
  {
    adres: "Paalstraat 37",
    naam: "Fietsen Van Dyck",
    soort: "vestigingseenheid",
    register: "Actief",
    laatste: "2026-09-11",
    zekerheid: "Hoog",
    voorstel: "Geen actie",
    voorstelLang: "Record klopt en is recent bevestigd.",
    vestNr: "2.240.117.669",
    ondNr: "0479.220.813",
    zetel: "Paalstraat 37, Schoten",
    rechtstoestand: "Normale toestand",
    contact: "03 658 99 04 · winkel@fietsenvandyck.be",
    contactNiveau: "vestiging",
    contactBron: "eigen website, 11-09-2026",
    bewijs: [
      {
        waarneming: "Website met openingsuren, telefoon opgenomen",
        bron: "eigen website",
        datum: "2026-09-11",
        url: "#",
      },
    ],
    x: 52,
    y: 34,
  },
  {
    adres: "Paalstraat 45",
    naam: "Bloemen Mira (pop-up)",
    soort: "niet in register",
    register: "Ontbreekt",
    laatste: "2026-09-12",
    zekerheid: "Middel",
    voorstel: "Nazicht: nieuwe vestiging ontbreekt",
    voorstelLang:
      "Nieuwe zaak sinds juli 2026, nog geen spoor in het register. Voorstel: onthaalbrief lokale economie versturen en de vestiging opvolgen.",
    vestNr: "ontbreekt",
    ondNr: "onbekend",
    zetel: "Onbekend",
    rechtstoestand: "n.v.t.",
    contact: "contactgegevens onbekend",
    contactNiveau: "geen bron",
    contactBron: "enkel sociale media zonder nummer",
    bewijs: [
      {
        waarneming: "Actief profiel met posts sinds 2026-07",
        bron: "sociale media",
        datum: "2026-09-12",
        url: "#",
      },
    ],
    x: 60,
    y: 41,
  },
  {
    adres: "Paalstraat 52",
    naam: "Boekhandel 't Blad",
    soort: "vestigingseenheid",
    register: "Actief",
    laatste: "2026-09-05",
    zekerheid: "Hoog",
    voorstel: "Bevestigen: stopzetting",
    voorstelLang:
      "Pand leeg met te-huur-bord, website offline. Voorstel: vestiging markeren als stopgezet per 2026-08 en de onderneming informeren.",
    vestNr: "2.155.909.284",
    ondNr: "0501.337.760",
    zetel: "Paalstraat 52, Schoten",
    rechtstoestand: "Normale toestand",
    contact: "03 680 12 45 (niet meer in dienst)",
    contactNiveau: "vestiging",
    contactBron: "GeoJSON, gecontroleerd 05-09-2026",
    bewijs: [
      {
        waarneming: "Pand leeg, te-huur-bord van makelaar",
        bron: "terreinbezoek",
        datum: "2026-09-05",
        url: "#",
      },
      {
        waarneming: "Website offline, domein te koop",
        bron: "DNS-controle",
        datum: "2026-09-05",
        url: "#",
      },
    ],
    x: 68,
    y: 36,
  },
  {
    adres: "Paalstraat 58",
    naam: "Apotheek Paalstraat",
    soort: "vestigingseenheid",
    register: "Actief",
    laatste: "2026-09-09",
    zekerheid: "Hoog",
    voorstel: "Geen actie",
    voorstelLang: "Bevestigd via beroepsregister en eigen website.",
    vestNr: "2.199.043.518",
    ondNr: "0644.771.290",
    zetel: "Paalstraat 58, Schoten",
    rechtstoestand: "Normale toestand",
    contact: "03 645 33 21",
    contactNiveau: "vestiging",
    contactBron: "beroepsregister apothekers",
    bewijs: [
      {
        waarneming: "Opgenomen in het beroepsregister met wachtdienst",
        bron: "beroepsregister",
        datum: "2026-09-09",
        url: "#",
      },
    ],
    x: 76,
    y: 33,
  },
  {
    adres: "Paalstraat 63",
    naam: "Tuinaanleg Claes Comm.V",
    soort: "vestiging · zetel Brecht",
    register: "Actief",
    laatste: "2026-06-14",
    zekerheid: "Middel",
    voorstel: "Ter controle: activiteit elders",
    voorstelLang:
      "Vestiging hier geregistreerd, maar alle publieke sporen wijzen naar de zetel in Brecht. Voorstel: nagaan of de vestiging nog dienstig is.",
    vestNr: "2.288.660.147",
    ondNr: "0779.114.552",
    zetel: "Kerkstraat 9, Brecht",
    rechtstoestand: "Normale toestand",
    contact: "03 313 88 01",
    contactNiveau: "centrale zetel (Brecht)",
    contactBron: "eigen website",
    bewijs: [
      {
        waarneming: "Omgevingsvergunning 2025 op dit adres",
        bron: "omgevingsloket",
        datum: "2025-11-02",
        url: "#",
      },
      {
        waarneming: "Website vermeldt enkel het adres in Brecht",
        bron: "eigen website",
        datum: "2026-06-14",
        url: "#",
      },
    ],
    x: 84,
    y: 39,
  },
  {
    adres: "Churchilllaan 8",
    naam: "Garage Stevens",
    soort: "vestigingseenheid",
    register: "Actief",
    laatste: "2026-09-02",
    zekerheid: "Hoog",
    voorstel: "Geen actie",
    voorstelLang: "Bevestigd via website en kaartdienst.",
    vestNr: "2.117.554.903",
    ondNr: "0466.223.019",
    zetel: "Churchilllaan 8, Schoten",
    rechtstoestand: "Normale toestand",
    contact: "03 658 12 77",
    contactNiveau: "vestiging",
    contactBron: "eigen website",
    bewijs: [
      {
        waarneming: "Website en kaartdienst stemmen overeen",
        bron: "kaartdienst",
        datum: "2026-09-02",
        url: "#",
      },
    ],
    x: 30,
    y: 62,
  },
  {
    adres: "Churchilllaan 22",
    naam: "Kruidenier Deniz",
    soort: "niet in register op dit adres",
    register: "Ontbreekt",
    laatste: "2026-09-06",
    zekerheid: "Middel",
    voorstel: "Nazicht: vestiging ontbreekt",
    voorstelLang:
      "Zichtbaar open kruidenier zonder vestigingseenheid. Voorstel: contact opnemen en de vestiging laten registreren.",
    vestNr: "ontbreekt",
    ondNr: "onbekend",
    zetel: "Onbekend",
    rechtstoestand: "n.v.t.",
    contact: "contactgegevens onbekend",
    contactNiveau: "geen bron",
    contactBron: "—",
    bewijs: [
      {
        waarneming: "Uithangbord, open tijdens bezoek",
        bron: "terreinbezoek",
        datum: "2026-09-06",
        url: "#",
      },
    ],
    x: 30,
    y: 74,
  },
];
